### ISSUE TITLE
[Feature reques] Class name for input element

### ISSUE THREAD

**Issue by petterkj** [BosNaufal/vue2-autocomplete#3]
I'm using twitter bootstrap, would be great if I could add "form-control" to the underlying `<input>` element.

**Comment by madr** [comment]
@petterkj This can be achieved fairly straight-forward by removing `-input` on className in `autocomplete.vue` and rebuild the bundle (`npm run bundle`), and then setting the class in the component:

```html
<autocomplete
    ...
    class-name='form-control'>
```

I did this recently in a project with Twitter Bootstrap.

**Comment by madr** [comment]
On a related note: I would like to suggest to take this a step further by adding an option that changes all markup in the component, so that the list of options also uses the same markup as Typeahead, Twitter Bootstrap:s own autocomplete solution.

I imagine `twitter-bootstrap: true` or something like that.

**Comment by BosNaufal** [comment]
Hi @madr @petterkj 
Now you can use the ```classes``` props! :grin: :+1: 
https://github.com/BosNaufal/vue2-autocomplete#classes-object
